import unittest
import pytest
from random import randint
from materials_commons.api import create_project, Experiment


def fake_name(prefix):
    number = "%05d" % randint(0, 99999)
    return prefix + number

@pytest.mark.skip("TestFile - later")
class TestFile(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.user = "another@test.mc"
        cls.apikey = "another-bogus-account"
        project_name = fake_name("TestApikeyProject-")
        description = "Test project generated by automated test"
        cls.project = create_project(project_name, description, apikey=cls.apikey)

# From Project - Move to File
# def add_file_using_directory(self, directory, file_name, local_path, verbose=False, limit=50):
# def add_file_by_local_path(self, local_path, verbose=False, limit=50):
# def get_by_local_path(self, local_path):
# def file_exists_by_local_path(self, local_path, checksum=False):

# # def get_all_files(self):
# # def add_files(self, files_list):
