import unittest
from random import randint
from materials_commons.api import create_project, Experiment


def fake_name(prefix):
    number = "%05d" % randint(0, 99999)
    return prefix + number


class TestProcess(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.user = "another@test.mc"
        cls.apikey = "another-bogus-account"
        project_name = fake_name("TestApikeyProject-")
        description = "Test project generated by automated test"
        cls.project = create_project(project_name, description, apikey=cls.apikey)

# from Project - Move to Process
# def get_all_processes(self):
# def get_process_by_id(self, process_id):
