import unittest
import pytest
from random import randint
from os import environ
from os import path as os_path
from os.path import getsize
from pathlib import Path
from mcapi import set_remote_config_url, get_remote_config_url
from mcapi import create_project

url = 'http://mctest.localhost/api'


def fake_name(prefix):
    number = "%05d" % randint(0, 99999)
    return prefix + number


class TestMove(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        set_remote_config_url(url)
        cls.project_name = fake_name("TestMoveProject-")
        description = "Test project generated by automated test"
        project = create_project(cls.project_name, description)
        cls.project_id = project.id
        cls.project = project
        print ''
        print project.name

        cls.top_directory = project.get_top_directory()
        cls.test_dir_path_a = "/TestForMove/A"
        cls.directory_a = project.add_directory(cls.test_dir_path_a)
        cls.test_dir_path_b = "/TestForMove/A/B"
        cls.directory_b = project.add_directory(cls.test_dir_path_b)
        cls.test_dir_path_c = "/TestForMove/A/B/C"
        cls.directory_c = project.add_directory(cls.test_dir_path_c)
        cls.test_dir_path_d = "/TestForMove/A/B/D"
        cls.directory_d = project.add_directory(cls.test_dir_path_d)
        cls.test_dir_path_e = "/TestForMove/A/E"
        cls.directory_e = project.add_directory(cls.test_dir_path_e)
        cls.test_dir_path_f = "/TestForMove/F"
        cls.directory_f = project.add_directory(cls.test_dir_path_f)

        cls.directory_for_move_name = "/FilesForMove"
        cls.directory_for_move = project.add_directory(cls.directory_for_move_name)
        if 'TEST_DATA_DIR' in environ:
            test_path = os_path.abspath(environ['TEST_DATA_DIR'])
            file_path = os_path.join(test_path, 'test_upload_data', 'fractal.jpg')
            path = Path(file_path)
            cls.file_path = str(path.absolute())
            cls.byte_count = getsize(file_path)
            cls.original_filename = "FileForMove.jpg"
            cls.test_file = project.add_file_using_directory(
                cls.directory_for_move,
                cls.original_filename,
                cls.file_path
            )

    def test_is_setup_correctly(self):
        self.assertTrue('TEST_DATA_DIR' in environ)
        self.assertIsNotNone(self.file_path)
        self.assertTrue(os_path.isfile(self.file_path))
        self.assertIsNotNone(self.test_file)
        self.assertEqual(self.test_file.size, self.byte_count)
        self.assertEqual(self.test_file.name, self.original_filename)

        self.assertEqual(get_remote_config_url(), url)
        self.assertIsNotNone(self.project)
        self.assertIsNotNone(self.project.name)
        self.assertEqual(self.project_name, self.project.name)
        self.assertIsNotNone(self.project.id)
        self.assertEqual(self.project_id, self.project.id)
        self.assertEqual(self.top_directory.name, self.project.name)
        self.assertEqual(self.directory_a.name, self.project.name + self.test_dir_path_a)
        self.assertEqual(self.directory_b.name, self.project.name + self.test_dir_path_b)

        directory_list = self.project.get_directory_list(self.test_dir_path_c)
        self.assertIsNotNone(directory_list)
        self.assertEqual(len(directory_list), 4)
        self.assertEqual(directory_list[1].name, self.project.name + self.test_dir_path_a)
        self.assertEqual(directory_list[2].name, self.project.name + self.test_dir_path_b)
        self.assertEqual(directory_list[3].name, self.project.name + self.test_dir_path_c)

        file = self.test_file
        self.assertEqual(file._directory.id,self.directory_for_move.id);
        child_list = self.directory_for_move.get_children();
        probe = child_list[0]
        self.assertEqual(file.id,probe.id)
        self.assertEqual(file.name,probe.name)
        self.assertEqual(file._directory.id, probe._directory.id)
        self.assertEqual(file._directory.id,self.directory_for_move.id)

    def test_move_file(self):
        test_file = self.test_file
        target = self.directory_b
        updated_file = test_file.move(target)

        self.assertEqual(updated_file.id, test_file.id)
        self.assertEqual(updated_file._project, self.project)
        directory_list = self.project.get_directory_list(self.directory_for_move_name)
        directory = directory_list[-1]
        self.assertEqual(directory.id, self.directory_for_move.id)
        self.assertEqual(directory._project, self.project)
        child_list = directory.get_children()
        print(child_list)
        for child in child_list:
            print child.name

    # def test_move_directory(self):
    #     directory = self.directory_b
    #     self.assertEqual(directory._project, self.project)
    #     self.assertEqual(directory.name, self.project.name + self.test_dir_path_b)
    #     self.assertEqual(self.directory_c.name, self.project.name + self.test_dir_path_c)
    #     updatedDirectory = directory.move("XX")
    #     self.assertEqual(updatedDirectory.path, self.project.name + "/TestFormove/A/XX")
    #
    # def test_cannot_move_top_level_directory(self):
    #     top_directory = self.project.get_top_directory()
    #     self.assertEqual(top_directory.path, self.project.name)
    #     with pytest.raises(Exception):
    #         updatedDirectory = top_directory.move("XX")
    #     top_directory = self.project.get_top_directory()
    #     self.assertEqual(top_directory.path, self.project.name)
