#!/usr/bin/env python

# temporary home before integrating else where
from __future__ import unicode_literals

import argparse
import imp
from io import StringIO
import sys

from materials_commons.cli.parser import CommonsCLIParser

if __name__ == "__main__":
    cli = CommonsCLIParser(sys.argv)
